---

data_path_c1: #path to dataset 1 
img_min_c1: -57
img_max_c1: 164

data_path_c2: #path to dataset 2
img_min_c2: -57
img_max_c2: 164

data_path_c3: #path to dataset 3
img_min_c3: -57
img_max_c3: 164

data_path_c4: #path to dataset 4
img_min_c4: -57
img_max_c4: 164

train_batch_size: 2
val_batch_size: 1
num_workers: 12

learning_rate: 0.0001
max_epochs: 250



